### ISSUE TITLE
Open failed on Miui 13

### ISSUE THREAD

**Issue by chinnsenn** [WindySha/bypassHiddenApiRestriction#3]
在 MIUI 13 上解除限制失败，导致 App 停留在启动界面，日志如下，经小米云真机 小米 12 Pro 测试
```
2022-02-08 16:35:21.044 9752-9752/com.annuochina.insurance.pre I/a.insurance.pr: Late-enabling -Xcheck:jni
2022-02-08 16:35:21.113 9752-9752/com.annuochina.insurance.pre D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10736; state: DISABLED
2022-02-08 16:35:21.124 9752-9769/com.annuochina.insurance.pre D/AppScoutStateMachine: 9752-ScoutStateMachinecreated
2022-02-08 16:35:21.128 9752-9752/com.annuochina.insurance.pre V/GraphicsEnvironment: ANGLE Developer option for 'com.annuochina.insurance.pre' set to: 'default'
2022-02-08 16:35:21.128 9752-9752/com.annuochina.insurance.pre V/GraphicsEnvironment: Updatable production driver is not supported on the device.
2022-02-08 16:35:21.130 9752-9752/com.annuochina.insurance.pre I/ForceDarkHelperStubImpl: initialize for com.annuochina.insurance.pre , ForceDarkOrigin
2022-02-08 16:35:21.130 9752-9752/com.annuochina.insurance.pre D/OpenGLRenderer: JNI_OnLoad success
2022-02-08 16:35:21.130 9752-9752/com.annuochina.insurance.pre I/MiuiForceDarkConfig: setConfig density:3.500000, mainRule:0, secondaryRule:0, tertiaryRule:0
2022-02-08 16:35:21.131 9752-9752/com.annuochina.insurance.pre D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
2022-02-08 16:35:21.132 9752-9752/com.annuochina.insurance.pre D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
2022-02-08 16:35:21.134 9752-9752/com.annuochina.insurance.pre I/MultiDex: VM with version 2.1.0 has multidex support
2022-02-08 16:35:21.134 9752-9752/com.annuochina.insurance.pre I/MultiDex: Installing application
2022-02-08 16:35:21.134 9752-9752/com.annuochina.insurance.pre I/MultiDex: VM has multidex support, MultiDex support library is disabled.
2022-02-08 16:35:21.136 9752-9752/com.annuochina.insurance.pre D/Bypass_DlFunctions: get elf base /apex/com.android.art/lib64/libnativebridge.so: 0x720511f000
2022-02-08 16:35:21.136 9752-9752/com.annuochina.insurance.pre I/Bypass_DlFunctions: get trampoline_address_from_system_lib result : 0x7205121000 
2022-02-08 16:35:23.626 9752-9772/com.annuochina.insurance.pre W/MIUIScout App: Enter APP_SCOUT_WARNING State
2022-02-08 16:35:23.635 9752-9796/com.annuochina.insurance.pre W/MIUIScout App: Event:APP_SCOUT_WARNING Thread:main backtrace:
        at com.wind.hiddenapi.bypass.HiddenApiBypass.setHiddenApiExemptions(Native Method)
        at com.wind.hiddenapi.bypass.HiddenApiBypass.startBypass(HiddenApiBypass.java:12)
        at com.annuochina.insurance.App.attachBaseContext(App.kt:53)
        at android.app.Application.attach(Application.java:333)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1369)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6896)
        at android.app.ActivityThread.access$1600(ActivityThread.java:264)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8088)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2022-02-08 16:35:23.636 9752-9758/com.annuochina.insurance.pre I/a.insurance.pr: Thread[3,tid=9758,WaitingInMainSignalCatcherLoop,Thread*=0xb4000070622fdc50,peer=0x12e80ea8,"Signal Catcher"]: reacting to signal 3
2022-02-08 16:35:23.636 9752-9758/com.annuochina.insurance.pre I/a.insurance.pr: 
2022-02-08 16:35:23.657 9752-9758/com.annuochina.insurance.pre I/a.insurance.pr: Wrote stack traces to tombstoned
2022-02-08 16:35:26.129 9752-9772/com.annuochina.insurance.pre W/MIUIScout App: Enter APP_SCOUT_HANG state
2022-02-08 16:35:26.130 9752-9854/com.annuochina.insurance.pre W/MIUIScout App: Event:APP_SCOUT_HANG Thread:main backtrace:
        at com.wind.hiddenapi.bypass.HiddenApiBypass.setHiddenApiExemptions(Native Method)
        at com.wind.hiddenapi.bypass.HiddenApiBypass.startBypass(HiddenApiBypass.java:12)
        at com.annuochina.insurance.App.attachBaseContext(App.kt:53)
        at android.app.Application.attach(Application.java:333)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1178)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1369)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6896)
        at android.app.ActivityThread.access$1600(ActivityThread.java:264)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2103)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at android.app.ActivityThread.main(ActivityThread.java:8088)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2022-02-08 16:35:26.134 9752-9758/com.annuochina.insurance.pre I/a.insurance.pr: Thread[3,tid=9758,WaitingInMainSignalCatcherLoop,Thread*=0xb4000070622fdc50,peer=0x12cc0ea8,"Signal Catcher"]: reacting to signal 3
2022-02-08 16:35:26.134 9752-9758/com.annuochina.insurance.pre I/a.insurance.pr: 
2022-02-08 16:35:26.151 9752-9758/com.annuochina.insurance.pre I/a.insurance.pr: Wrote stack traces to tombstoned
```

**Comment by WindySha** [comment]
Update version to 1.1.0, and this bug is fixed.
```
implementation 'io.github.windysha:bypassHiddenApiRestriction:1.1.0'
```

**Comment by FightingForDevelop** [comment]
Do you solve this problem? I have the same with you.

**Comment by chinnsenn** [comment]
@FightingForDevelop Yes，update to latest version

**Comment by FightingForDevelop** [comment]
> @FightingForDevelop Yes，update to latest version
Update whose version? The MIUI or other one?And the version code is? Now my MIUI version is 13.0.6.0稳定版

**Comment by FightingForDevelop** [comment]
@chinnsenn Update whose version? The MIUI or other one?And the version code is? Now my MIUI version is 13.0.6.0稳定版

**Comment by FightingForDevelop** [comment]
@WindySha How Do you solve this problem? I have the same with you.I don't rely on bypassHiddenApiRestriction.Just my project has this qustion.
